# Generated by Django 4.2.4 on 2023-08-13 19:32

from django.db import migrations, models
import gym_manager_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ("gym_manager_api", "0007_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[gym_manager_api.validators.phone_number_validator],
            ),
        ),
        migrations.CreateModel(
            name="EventException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("move_from", models.DateTimeField()),
                ("move_to", models.DateTimeField()),
                ("attendees", models.ManyToManyField(to="gym_manager_api.student")),
                ("group", models.ManyToManyField(to="gym_manager_api.group")),
                ("instructor", models.ManyToManyField(to="gym_manager_api.instructor")),
            ],
        ),
    ]
